<template><div><h3 id="第二、三个月-7-23-9-16" tabindex="-1"><a class="header-anchor" href="#第二、三个月-7-23-9-16"><span>第二、三个月（7.23-9.16）</span></a></h3>
<p><strong>一、我做了什么</strong></p>
<ol>
<li>
<p>编写js和java接口，练习SQL语句，与第一个月相同</p>
</li>
<li>
<p>摸鱼</p>
</li>
</ol>
<p><strong>二、我学到了什么</strong></p>
<ol>
<li>
<p>解决问题方面，应该先构思如何解决问题再动手实现，切忌走一步看一步。</p>
</li>
<li>
<p>代码要写注释😅某大肚子没脖子的程序员说的就是你。</p>
</li>
<li>
<p>SQL和jquery的语法有很大提升。</p>
</li>
</ol>
<p><strong>三、我遇到的问题</strong></p>
<ol>
<li>
<p>java基础，如BigDecimal类的相关方法。</p>
</li>
<li>
<p>SQL基础，如各种函数的使用，以及左关联等的使用。</p>
</li>
<li>
<p>缺乏解决问题的思路，或者对需求的规范实现方法没有清晰的构思。</p>
</li>
<li>
<p>公司的代码太老旧，感觉与主流技术栈脱节，打算主要以java、js、SQL的基础练手为主。</p>
</li>
<li>
<p>代码不够健壮。</p>
</li>
</ol>
<p><strong>四、解决方法</strong></p>
<ol>
<li>
<p>去论坛多看看主流的解决问题的思路，看看别人的代码是怎么写的。</p>
</li>
<li>
<p>学习目前的主流技术栈，可以找找自己感兴趣的项目学习。</p>
</li>
<li>
<p>提升代码健壮性，见<RouteLink to="/technologyStack/robustnessOfCode.html">如何提升代码健壮性</RouteLink>。</p>
</li>
</ol>
</div></template>


