<template><div><h1 id="如何提升代码健壮性" tabindex="-1"><a class="header-anchor" href="#如何提升代码健壮性"><span>如何提升代码健壮性</span></a></h1>
<blockquote>
<p>工作近三个月，明显感受到自己写的代码臃肿、适配性差。尽管有公司项目旧、无规范的原因，但是自身的代码也有很大问题。所以问了ai如何提升代码健壮性。以下。</p>
</blockquote>
<h2 id="早返回-guard-clause" tabindex="-1"><a class="header-anchor" href="#早返回-guard-clause"><span>早返回（Guard Clause）</span></a></h2>
<ul>
<li>
<p>问题代码：代码不要层层嵌套，往往读到底才能了解代码目的。</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#8FBCBB"> User</span><span style="color:#88C0D0"> createUser</span><span style="color:#ECEFF4">(</span><span style="color:#8FBCBB">CreateUserDto</span><span style="color:#D8DEE9FF"> dto</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">dto </span><span style="color:#81A1C1">!=</span><span style="color:#81A1C1"> null</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9">dto</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getName</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> !=</span><span style="color:#81A1C1"> null</span><span style="color:#81A1C1"> &#x26;&#x26;</span><span style="color:#81A1C1"> !</span><span style="color:#D8DEE9">dto</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getName</span><span style="color:#ECEFF4">().</span><span style="color:#88C0D0">isBlank</span><span style="color:#ECEFF4">())</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">            if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9">dto</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getAge</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> !=</span><span style="color:#81A1C1"> null</span><span style="color:#81A1C1"> &#x26;&#x26;</span><span style="color:#D8DEE9"> dto</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getAge</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> >=</span><span style="color:#B48EAD"> 18</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#8FBCBB">                User</span><span style="color:#D8DEE9"> user</span><span style="color:#81A1C1"> =</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> User</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">                user</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">setName</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">dto</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getName</span><span style="color:#ECEFF4">().</span><span style="color:#88C0D0">trim</span><span style="color:#ECEFF4">())</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">                user</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">setAge</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">dto</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getAge</span><span style="color:#ECEFF4">())</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">                return</span><span style="color:#D8DEE9"> userRepository</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">save</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">user</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">            }</span><span style="color:#81A1C1"> else</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">                throw</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> IllegalArgumentException</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">年龄必须≥18</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">            }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">        }</span><span style="color:#81A1C1"> else</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">            throw</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> IllegalArgumentException</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">姓名不能为空</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">        }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span><span style="color:#81A1C1"> else</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        throw</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> IllegalArgumentException</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">dto 不能为空</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
<li>
<p>重构后：非法场景提前 return，主干逻辑顶格。</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#8FBCBB"> User</span><span style="color:#88C0D0"> createUser</span><span style="color:#ECEFF4">(</span><span style="color:#8FBCBB">CreateUserDto</span><span style="color:#D8DEE9FF"> dto</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">dto </span><span style="color:#81A1C1">==</span><span style="color:#81A1C1"> null</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1"> throw</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> IllegalArgumentException</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">dto 不能为空</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9">dto</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getName</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> ==</span><span style="color:#81A1C1"> null</span><span style="color:#81A1C1"> ||</span><span style="color:#D8DEE9"> dto</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getName</span><span style="color:#ECEFF4">().</span><span style="color:#88C0D0">isBlank</span><span style="color:#ECEFF4">())</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    throw</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> IllegalArgumentException</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">姓名不能为空</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9">dto</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getAge</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> ==</span><span style="color:#81A1C1"> null</span><span style="color:#81A1C1"> ||</span><span style="color:#D8DEE9"> dto</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getAge</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> &#x3C;</span><span style="color:#B48EAD"> 18</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    throw</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> IllegalArgumentException</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">年龄必须≥18</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#8FBCBB">User</span><span style="color:#D8DEE9"> user</span><span style="color:#81A1C1"> =</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> User</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">user</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">setName</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">dto</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getName</span><span style="color:#ECEFF4">().</span><span style="color:#88C0D0">trim</span><span style="color:#ECEFF4">())</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">user</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">setAge</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">dto</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getAge</span><span style="color:#ECEFF4">())</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">return</span><span style="color:#D8DEE9"> userRepository</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">save</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">user</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
<li>
<p>单测（JUnit 5 + assertThrows）：</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-java"><code><span class="line"><span class="line"><span style="color:#ECEFF4">@</span><span style="color:#D08770">Test</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">void</span><span style="color:#88C0D0"> shouldRejectNullDto</span><span style="color:#ECEFF4">()</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">assertThrows</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">IllegalArgumentException</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">class</span><span style="color:#ECEFF4">,</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">            ()</span><span style="color:#8FBCBB"> -></span><span style="color:#D8DEE9"> service</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">createUser</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">null</span><span style="color:#ECEFF4">),</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">            "</span><span style="color:#A3BE8C">dto 不能为空</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
</ul>
<h2 id="表驱动消灭-if-else-链" tabindex="-1"><a class="header-anchor" href="#表驱动消灭-if-else-链"><span>表驱动消灭 if/else 链</span></a></h2>
<ul>
<li>
<p>问题代码：业务分支一多就膨胀。</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-java"><code><span class="line"><span class="line"><span style="color:#616E88">// 啰嗦</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#8FBCBB"> BigDecimal</span><span style="color:#88C0D0"> discount</span><span style="color:#ECEFF4">(</span><span style="color:#8FBCBB">OrderType</span><span style="color:#D8DEE9FF"> type</span><span style="color:#ECEFF4">,</span><span style="color:#8FBCBB"> BigDecimal</span><span style="color:#D8DEE9FF"> amount</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">type </span><span style="color:#81A1C1">==</span><span style="color:#D8DEE9"> OrderType</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">NORMAL</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1"> return</span><span style="color:#D8DEE9"> amount</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">multiply</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">new</span><span style="color:#88C0D0"> BigDecimal</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">0.95</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">))</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    else</span><span style="color:#81A1C1"> if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">type </span><span style="color:#81A1C1">==</span><span style="color:#D8DEE9"> OrderType</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">VIP</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1"> return</span><span style="color:#D8DEE9"> amount</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">multiply</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">new</span><span style="color:#88C0D0"> BigDecimal</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">0.90</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">))</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    else</span><span style="color:#81A1C1"> if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">type </span><span style="color:#81A1C1">==</span><span style="color:#D8DEE9"> OrderType</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">SVIP</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1"> return</span><span style="color:#D8DEE9"> amount</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">multiply</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">new</span><span style="color:#88C0D0"> BigDecimal</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">0.85</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">))</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    else</span><span style="color:#81A1C1"> throw</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> IllegalArgumentException</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">未知类型</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
<li>
<p>重构后：Enum 自带行为，O(1) 查表，后续加类型只改枚举。</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">enum</span><span style="color:#D8DEE9FF"> OrderType </span><span style="color:#ECEFF4">{</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    NORMAL</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">BigDecimal</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">valueOf</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">0.95</span><span style="color:#ECEFF4">)),</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    VIP</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">BigDecimal</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">valueOf</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">0.90</span><span style="color:#ECEFF4">)),</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    SVIP</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">BigDecimal</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">valueOf</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">0.85</span><span style="color:#ECEFF4">))</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    private</span><span style="color:#81A1C1"> final</span><span style="color:#8FBCBB"> BigDecimal</span><span style="color:#D8DEE9"> rate</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">    OrderType</span><span style="color:#ECEFF4">(</span><span style="color:#8FBCBB">BigDecimal</span><span style="color:#D8DEE9"> rate</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span><span style="color:#81A1C1"> this</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">rate</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9FF"> rate</span><span style="color:#81A1C1">;</span><span style="color:#ECEFF4"> }</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    public</span><span style="color:#8FBCBB"> BigDecimal</span><span style="color:#88C0D0"> apply</span><span style="color:#ECEFF4">(</span><span style="color:#8FBCBB">BigDecimal</span><span style="color:#D8DEE9"> amount</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span><span style="color:#81A1C1"> return</span><span style="color:#D8DEE9"> amount</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">multiply</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">rate</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span><span style="color:#ECEFF4"> }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#8FBCBB"> BigDecimal</span><span style="color:#88C0D0"> discount</span><span style="color:#ECEFF4">(</span><span style="color:#8FBCBB">OrderType</span><span style="color:#D8DEE9FF"> type</span><span style="color:#ECEFF4">,</span><span style="color:#8FBCBB"> BigDecimal</span><span style="color:#D8DEE9FF"> amount</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    Objects</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">requireNonNull</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">type</span><span style="color:#ECEFF4">,</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">type 不能为空</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    return</span><span style="color:#D8DEE9"> type</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">apply</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">amount</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
</ul>
<h2 id="重复校验逻辑集中化" tabindex="-1"><a class="header-anchor" href="#重复校验逻辑集中化"><span>重复校验逻辑集中化</span></a></h2>
<ul>
<li>
<p>问题代码：每个接口都手写非空、长度、范围判断。</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-java"><code><span class="line"><span class="line"><span style="color:#616E88">// 啰嗦，到处复制</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">name </span><span style="color:#81A1C1">==</span><span style="color:#81A1C1"> null</span><span style="color:#81A1C1"> ||</span><span style="color:#D8DEE9"> name</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">length</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> &#x3C;</span><span style="color:#B48EAD"> 2</span><span style="color:#81A1C1"> ||</span><span style="color:#D8DEE9"> name</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">length</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> ></span><span style="color:#B48EAD"> 20</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    throw</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> IllegalArgumentException</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">姓名长度 2-20</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
<li>
<p>重构后：封装校验器 + 自定义异常，统一错误码。</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#81A1C1"> final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Validator</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    private</span><span style="color:#88C0D0"> Validator</span><span style="color:#ECEFF4">()</span><span style="color:#ECEFF4"> {}</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    public</span><span style="color:#81A1C1"> static</span><span style="color:#8FBCBB"> String</span><span style="color:#88C0D0"> validName</span><span style="color:#ECEFF4">(</span><span style="color:#8FBCBB">String</span><span style="color:#D8DEE9"> name</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">name </span><span style="color:#81A1C1">==</span><span style="color:#81A1C1"> null</span><span style="color:#81A1C1"> ||</span><span style="color:#D8DEE9"> name</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">length</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> &#x3C;</span><span style="color:#B48EAD"> 2</span><span style="color:#81A1C1"> ||</span><span style="color:#D8DEE9"> name</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">length</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> ></span><span style="color:#B48EAD"> 20</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">            throw</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> BizException</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">400</span><span style="color:#ECEFF4">,</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">NAME_INVALID</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">,</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">姓名长度 2-20</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        return</span><span style="color:#D8DEE9FF"> name</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// 使用</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">user</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">setName</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">Validator</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">validName</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">dto</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getName</span><span style="color:#ECEFF4">()))</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
</ul>
<h2 id="异常体系混乱" tabindex="-1"><a class="header-anchor" href="#异常体系混乱"><span>异常体系混乱</span></a></h2>
<ul>
<li>
<p>问题代码：直接抛出异常，无法判断异常来自用户还是服务器。</p>
</li>
<li>
<p>重构后：定义两类异常 + <code v-pre>@ControllerAdvice</code> 统一转 JSON。</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-java"><code><span class="line"><span class="line"><span style="color:#616E88">// 业务异常，前端 4xx</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> BizException</span><span style="color:#81A1C1"> extends</span><span style="color:#8FBCBB;font-weight:bold"> RuntimeException</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    private</span><span style="color:#81A1C1"> final</span><span style="color:#81A1C1"> int</span><span style="color:#D8DEE9"> code</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    public</span><span style="color:#88C0D0"> BizException</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">int</span><span style="color:#D8DEE9"> code</span><span style="color:#ECEFF4">,</span><span style="color:#8FBCBB"> String</span><span style="color:#D8DEE9"> message</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span><span style="color:#81A1C1"> super</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">message</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span><span style="color:#81A1C1"> this</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">code</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9FF"> code</span><span style="color:#81A1C1">;</span><span style="color:#ECEFF4"> }</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    public</span><span style="color:#81A1C1"> int</span><span style="color:#88C0D0"> getCode</span><span style="color:#ECEFF4">()</span><span style="color:#ECEFF4"> {</span><span style="color:#81A1C1"> return</span><span style="color:#D8DEE9FF"> code</span><span style="color:#81A1C1">;</span><span style="color:#ECEFF4"> }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// 系统异常，前端 5xx</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> SysException</span><span style="color:#81A1C1"> extends</span><span style="color:#8FBCBB;font-weight:bold"> RuntimeException</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    public</span><span style="color:#88C0D0"> SysException</span><span style="color:#ECEFF4">(</span><span style="color:#8FBCBB">String</span><span style="color:#D8DEE9"> message</span><span style="color:#ECEFF4">,</span><span style="color:#8FBCBB"> Throwable</span><span style="color:#D8DEE9"> cause</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span><span style="color:#81A1C1"> super</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">message</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9FF"> cause</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span><span style="color:#ECEFF4"> }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">@</span><span style="color:#D08770">RestControllerAdvice</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> GlobalAdvice</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    @</span><span style="color:#D08770">ResponseStatus</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">HttpStatus</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">BAD_REQUEST</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    @</span><span style="color:#D08770">ExceptionHandler</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">BizException</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">class</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    public</span><span style="color:#8FBCBB"> Map</span><span style="color:#ECEFF4">&#x3C;</span><span style="color:#8FBCBB">String</span><span style="color:#ECEFF4">,</span><span style="color:#8FBCBB"> Object</span><span style="color:#ECEFF4">></span><span style="color:#88C0D0"> handleBiz</span><span style="color:#ECEFF4">(</span><span style="color:#8FBCBB">BizException</span><span style="color:#D8DEE9"> e</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        return</span><span style="color:#D8DEE9"> Map</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">of</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">code</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> e</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getCode</span><span style="color:#ECEFF4">(),</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">msg</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> e</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getMessage</span><span style="color:#ECEFF4">())</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    @</span><span style="color:#D08770">ResponseStatus</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">HttpStatus</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">INTERNAL_SERVER_ERROR</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    @</span><span style="color:#D08770">ExceptionHandler</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">SysException</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">class</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    public</span><span style="color:#8FBCBB"> Map</span><span style="color:#ECEFF4">&#x3C;</span><span style="color:#8FBCBB">String</span><span style="color:#ECEFF4">,</span><span style="color:#8FBCBB"> Object</span><span style="color:#ECEFF4">></span><span style="color:#88C0D0"> handleSys</span><span style="color:#ECEFF4">(</span><span style="color:#8FBCBB">SysException</span><span style="color:#D8DEE9"> e</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        return</span><span style="color:#D8DEE9"> Map</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">of</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">code</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">,</span><span style="color:#B48EAD"> 500</span><span style="color:#ECEFF4">,</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">msg</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">,</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">系统繁忙，请稍后重试</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
</ul>
<h2 id="魔法值硬编码-→-枚举-常量" tabindex="-1"><a class="header-anchor" href="#魔法值硬编码-→-枚举-常量"><span>魔法值硬编码 → 枚举 + 常量</span></a></h2>
<ul>
<li>
<p>问题代码：直接使用String硬编码</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">if</span><span style="color:#ECEFF4"> (</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">PAY_SUCCESS</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">equals</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">status</span><span style="color:#ECEFF4">))</span><span style="color:#ECEFF4"> {</span><span style="color:#ECEFF4"> ...</span><span style="color:#ECEFF4"> }</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
<li>
<p>重构后：使用枚举+常量</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">enum</span><span style="color:#D8DEE9FF"> PayStatus </span><span style="color:#ECEFF4">{</span><span style="color:#D8DEE9"> SUCCESS</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> FAIL</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> CLOSED</span><span style="color:#ECEFF4"> }</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9">PayStatus</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">SUCCESS</span><span style="color:#81A1C1"> ==</span><span style="color:#D8DEE9FF"> status</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span><span style="color:#ECEFF4"> ...</span><span style="color:#ECEFF4"> }</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
</ul>
<h2 id="过度-try-catch-→-利用-optional-自定义异常" tabindex="-1"><a class="header-anchor" href="#过度-try-catch-→-利用-optional-自定义异常"><span>过度 try-catch → 利用 Optional + 自定义异常</span></a></h2>
<ul>
<li>
<p>问题代码：到处捕获 NPE，代码臃肿。</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">try</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    return</span><span style="color:#D8DEE9"> order</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getItem</span><span style="color:#ECEFF4">().</span><span style="color:#88C0D0">getProduct</span><span style="color:#ECEFF4">().</span><span style="color:#88C0D0">getPrice</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span><span style="color:#81A1C1"> catch</span><span style="color:#ECEFF4"> (</span><span style="color:#8FBCBB">NullPointerException</span><span style="color:#D8DEE9"> e</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    return</span><span style="color:#D8DEE9"> BigDecimal</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">ZERO</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
<li>
<p>重构后：Optional 链式 + orElseThrow。</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">return</span><span style="color:#D8DEE9"> Optional</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">ofNullable</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">order</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">               .</span><span style="color:#88C0D0">map</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">Order</span><span style="color:#81A1C1">::</span><span style="color:#D8DEE9FF">getItem</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">               .</span><span style="color:#88C0D0">map</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">Item</span><span style="color:#81A1C1">::</span><span style="color:#D8DEE9FF">getProduct</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">               .</span><span style="color:#88C0D0">map</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">Product</span><span style="color:#81A1C1">::</span><span style="color:#D8DEE9FF">getPrice</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">               .</span><span style="color:#88C0D0">orElseThrow</span><span style="color:#ECEFF4">(()</span><span style="color:#8FBCBB"> -></span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> BizException</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">400</span><span style="color:#ECEFF4">,</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">PRICE_NOT_FOUND</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">,</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">价格缺失</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">))</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
</ul>
<h2 id="日志无重要信息" tabindex="-1"><a class="header-anchor" href="#日志无重要信息"><span>日志无重要信息</span></a></h2>
<ul>
<li>
<p>重构后：使用 Slf4j + MDC，ELK 可直接索引,打印出关键的变量。</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-java"><code><span class="line"><span class="line"><span style="color:#D8DEE9">MDC</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">put</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">orderNo</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> order</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getOrderNo</span><span style="color:#ECEFF4">())</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">log</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">info</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">订单处理完成, amount={}</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> order</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">getAmount</span><span style="color:#ECEFF4">())</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">MDC</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">clear</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
</ul>
</div></template>


